"""Drive the obstacle course with heading control, Space jump and R reset.

This is the legacy LQR/MPC course controller with oracle state by default. It
does not load the locomotion PPO policy. Resets start separate recorded segments.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import sys
import tarfile
import time
from contextlib import nullcontext
from copy import copy
from dataclasses import asdict
from pathlib import Path

import mujoco
import numpy as np

from wheel_legged_control.d1.control_loop import D1MotionCommand
from wheel_legged_control.d1.interactive import D1InteractiveSimulation
from wheel_legged_control.d1.terrain import D1_COURSE_SPAWNS

if __package__:
    from .d1_course_controls import CourseKeyboardCommands
    from .d1_keyboard_viewer import KeyboardViewer
else:
    from d1_course_controls import CourseKeyboardCommands
    from d1_keyboard_viewer import KeyboardViewer

ROOT = Path(__file__).resolve().parents[1]
ZONES = dict(zip(map(ord, "123456"), ("start", "rough", "ramp", "stairs", "bumps", "jump")))


def apply_course_events(simulation, viewer, cursor, on_reset, current_zone="start"):
    """Consume a snapshot of PRESS events exactly once, preserving their order.

    Core generated by Claude Opus; locally tightened required callback/teleop
    calls and input types. Callback-appended events wait until the next call.
    """
    events, end = viewer.events, len(viewer.events)
    if type(cursor) is not int:
        raise TypeError("event cursor must be an integer")
    if not 0 <= cursor <= end:
        raise ValueError("event cursor is outside the event log")
    for index in range(cursor, end):
        event = events[index]
        if (
            not isinstance(event, dict)
            or event.get("type") != "key"
            or type(event.get("action")) is not int
            or event["action"] != 1
            or type(event.get("key")) is not int
        ):
            continue
        zone = current_zone if event["key"] == ord("R") else ZONES.get(event["key"])
        if zone is not None:
            simulation.reset(zone)
            current_zone = zone
            if hasattr(viewer.commands, "set_state"):
                state = simulation.teleop._state
                viewer.commands.reset(float(state.base_rpy[2]), state.base_position[:2])
            else:
                viewer.commands.update_pressed(set())
            viewer.reset_camera()
            on_reset(zone, index)
        elif event["key"] in (32, ord("J")):
            simulation.teleop.handle_key(32)
    return end


def _sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _json(path, value):
    with path.open("x") as stream:
        json.dump(value, stream, indent=2, sort_keys=True, allow_nan=False)
        stream.write("\n")


def _snapshot(output):
    paths = {Path(__file__).resolve(), ROOT / "pyproject.toml"}
    paths.update(
        ROOT / "scripts" / name
        for name in ("d1_course_controls.py", "d1_keyboard_commands.py",
                     "d1_keyboard_viewer.py", "d1_terrain_display.py")
    )
    for module in tuple(sys.modules.values()):
        file = getattr(module, "__file__", None)
        if file and str(ROOT / "src/wheel_legged_control") in file and file.endswith(".py"):
            paths.add(Path(file).resolve())
    paths.update(
        path for path in (ROOT / "src/wheel_legged_control/d1/assets").rglob("*") if path.is_file()
    )
    hashes = {str(path.relative_to(ROOT)): _sha(path) for path in sorted(paths)}
    with tarfile.open(output / "source.tar.gz", "w:gz") as archive:
        for path in sorted(paths):
            archive.add(path, arcname=str(path.relative_to(ROOT)), recursive=False)
    return hashes


def run(
    simulation,
    output,
    *,
    seconds=600.0,
    zone="start",
    commands=None,
    viewer_factory=KeyboardViewer,
    realtime=True,
):
    """Record commands before step, integrated states after step, and every reset.

    ``viewer_factory=None`` runs a headless zero-command smoke. Tests can inject
    a fake viewer, clock and input stream while using the actual MuJoCo plant.
    """
    output = Path(output).absolute()
    if any(path.is_symlink() for path in (output, *output.parents)):
        raise ValueError("output must not use symlinks")
    if output.exists():
        raise FileExistsError(output)
    if isinstance(seconds, bool) or not math.isfinite(seconds) or seconds <= 0:
        raise ValueError("seconds must be finite and positive")
    if zone not in D1_COURSE_SPAWNS:
        raise ValueError("unknown course zone")
    if simulation.teleop.residual_policy is not None:
        raise ValueError("course driving does not accept a residual policy")
    commands = CourseKeyboardCommands() if commands is None else commands
    if isinstance(commands, CourseKeyboardCommands):
        simulation.teleop.controller.low_level.wheel_velocity_gain = commands.wheel_velocity_gain
    simulation.reset(zone)
    if hasattr(commands, "set_state"):
        state = simulation.teleop._state
        commands.reset(float(state.base_rpy[2]), state.base_position[:2])
    plant = simulation.plant
    output.mkdir(parents=True, exist_ok=False)
    hashes = _snapshot(output)
    mujoco.mj_saveModel(plant.model, str(output / "model.mjb"), None)
    protocol = {
        "schema": "d1-course-heading-driving-v2",
        "arena": "course",
        "initial_zone": zone,
        "requested_seconds": seconds,
        "control_dt_s": plant.control_dt,
        "physics_dt_s": float(plant.model.opt.timestep),
        "sampling_mode": plant.sampling_mode,
        "controller_class": type(simulation.teleop.controller).__name__,
        "state_mode": simulation.teleop.state_mode,
        "policy": "none",
        "contact_allocation": simulation.teleop.contact_allocation,
        "controls": "W/S forward; Q/E desired heading; Space guarded jump; R simulation reset; X cancel; T/G height; 1..6 zones; Esc exit",
        "lateral_motion": "not implemented; A/D report unavailable; fixed wheels have no direct strafe command",
        "recovery": "R explicitly resets simulator to current zone spawn; not physical self-righting",
        "command_adapter": type(commands).__name__,
        "course_profile": "heading_with_wheel_speed_feedback_v2",
        "wheel_velocity_gain": simulation.teleop.controller.low_level.wheel_velocity_gain,
        "heading_feedback": {name: getattr(commands, name, None) for name in
                             ("heading_rate_rps", "heading_gain", "heading_damping",
                              "yaw_request_limit_rps")},
        "status_timing": "step() status describes the control computed before that interval; guards may alter the requested command",
        "state_timing": "qpos/qvel and segment_time_s are integrated plant.data snapshots after step; each reset adds an initial state",
        "legacy_measurement_timing": "legacy_mixed keeps the previous final physics substep derived measurements; they are not relabeled synchronized",
        "rendering": "copy plant.data and model; mj_forward for rendering runs only on the copy",
        "segment_rule": "never interpolate or measure displacement across different segment_id values",
        "compiled_model_sha256": _sha(output / "model.mjb"),
        "source_sha256": hashes,
        "terrain_geom_count": len(plant.terrain_geom_ids),
    }
    _json(output / "protocol.json", protocol)
    positions, velocities, state_segments, local_times, global_times = [], [], [], [], []
    segments, jump_phases = [], set()
    tick = 0
    viewer = None
    started = time.monotonic()
    reason, cursor = "duration", 0

    def record_state():
        positions.append(plant.data.qpos.copy())
        velocities.append(plant.data.qvel.copy())
        state_segments.append(len(segments) - 1)
        local_times.append(float(plant.data.time))
        global_times.append(tick * plant.control_dt)

    def start_segment(selected_zone, event_index):
        segments.append(
            {
                "segment_id": len(segments),
                "zone": selected_zone,
                "reset_event_index": event_index,
                "first_state_index": len(positions),
                "first_transition_index": tick,
                "reset_kind": "initial" if event_index is None else "operator_simulation_reset",
            }
        )
        record_state()

    start_segment(zone, None)
    try:
        if viewer_factory is not None:
            display_model = copy(plant.model)
            display_data = mujoco.MjData(display_model)
            mujoco.mj_copyData(display_data, display_model, plant.data)
            viewer = viewer_factory(
                display_model, display_data, commands, terrain_label=f"Course: {zone}"
            )
            viewer.controls_help = (
                "W / S\nQ / E\nSpace\nR\nX\nT / G\nA / D\nC / Esc",
                "Forward / reverse\nSet heading left / right\nGuarded jump\nReset upright at this zone's start\nCancel motion and heading\nRaise / lower body\nSide stepping not available\nReset camera / exit",
            )
        with (
            nullcontext(None) if viewer is None else viewer,
            (output / "telemetry.csv").open("x", newline="") as csv_stream,
        ):
            writer = None
            for _ in range(math.ceil(seconds / plant.control_dt)):
                wall_tick = time.monotonic()
                if hasattr(commands, "set_state"):
                    state = simulation.teleop._state
                    commands.set_state(
                        yaw_rad=float(state.base_rpy[2]), position_xy=state.base_position[:2],
                        forward_velocity_mps=float(state.base_linear_velocity_body[0]),
                        yaw_rate_rps=float(state.base_angular_velocity_body[2]),
                        fallen=bool(state.has_fallen()), simulation_time_s=float(plant.data.time),
                    )
                if viewer is not None:
                    viewer.poll(tick * plant.control_dt)
                if commands.stopped:
                    reason = "keyboard_escape"
                    break
                if viewer is not None and not viewer.is_running():
                    reason = "viewer_closed"
                    break
                if viewer is not None:
                    cursor = apply_course_events(
                        simulation, viewer, cursor, start_segment, segments[-1]["zone"]
                    )
                    viewer.terrain_label = f"Course: {segments[-1]['zone']}"
                requested = commands(float(plant.data.time))
                simulation.teleop.forward_velocity_mps = requested.forward_velocity_mps
                simulation.teleop.yaw_rate_rps = requested.yaw_rate_rps
                simulation.teleop.base_height_m = requested.clearance_m
                before_time, before_index = float(plant.data.time), len(positions) - 1
                status = simulation.step()
                tick += 1
                record_state()
                row = {
                    "tick": tick,
                    "segment_id": len(segments) - 1,
                    "zone": segments[-1]["zone"],
                    "state_before_index": before_index,
                    "state_after_index": len(positions) - 1,
                    "segment_before_time_s": before_time,
                    "segment_after_time_s": float(plant.data.time),
                    "total_time_s": tick * plant.control_dt,
                    "requested_forward_mps": requested.forward_velocity_mps,
                    "requested_yaw_rps": requested.yaw_rate_rps,
                    "requested_height_m": requested.clearance_m,
                    "operator_forward_mps": getattr(commands, "requested_forward_mps", requested.forward_velocity_mps),
                    "heading_target_rad": getattr(commands, "goal_yaw_rad", float(simulation.teleop._state.base_rpy[2])),
                    "actual_heading_rad": float(simulation.teleop._state.base_rpy[2]),
                    "input_status": getattr(commands, "message", "legacy input"),
                    **asdict(status),
                }
                jump_phases.add(status.jump_phase)
                if writer is None:
                    writer = csv.DictWriter(csv_stream, fieldnames=list(row))
                    writer.writeheader()
                writer.writerow(row)
                csv_stream.flush()
                if viewer is not None:
                    with viewer.lock():
                        mujoco.mj_copyData(display_data, display_model, plant.data)
                        viewer.cam.lookat[:] = display_data.qpos[:3]
                    viewer.set_status(
                        D1MotionCommand(
                            status.forward_velocity_mps, status.yaw_rate_rps, status.base_height_m
                        ),
                        tick * plant.control_dt,
                    )
                    viewer.extra_help = (
                        "1 start | 2 rough | 3 ramp | 4 stairs | 5 bumps | 6 jump zone\n"
                        f"Space jump: {status.jump_phase} | Safety: {status.safety_mode}\n"
                        f"Heading: {math.degrees(float(simulation.teleop._state.base_rpy[2])):+.1f} deg"
                        f" -> {math.degrees(getattr(commands, 'goal_yaw_rad', 0.0)):+.1f} deg\n"
                        f"{getattr(commands, 'message', '')}\n"
                        f"{protocol['controller_class']} / {protocol['state_mode']} | No PPO"
                    )
                    viewer.sync()
                if realtime:
                    time.sleep(max(0.0, plant.control_dt - (time.monotonic() - wall_tick)))
    except KeyboardInterrupt:
        reason = "keyboard_interrupt"
    except BaseException as exc:
        reason = "error"
        _json(output / "failure.json", {"type": type(exc).__name__, "message": str(exc)})
        raise
    finally:
        with (output / "states.npz").open("xb") as stream:
            np.savez_compressed(
                stream,
                qpos=np.asarray(positions),
                qvel=np.asarray(velocities),
                segment_id=np.asarray(state_segments),
                segment_time_s=np.asarray(local_times),
                total_time_s=np.asarray(global_times),
            )
        _json(output / "segments.json", segments)
        with (output / "keyboard_events.jsonl").open("x") as stream:
            for event in [] if viewer is None else viewer.events:
                stream.write(json.dumps(event, sort_keys=True, allow_nan=False) + "\n")
        changed = [name for name, digest in hashes.items() if _sha(ROOT / name) != digest]
        summary = {
            "schema": "d1-course-held-driving-summary-v1",
            "steps": tick,
            "integrated_duration_s": tick * plant.control_dt,
            "segments": len(segments),
            "stop_reason": reason,
            "wall_seconds": time.monotonic() - started,
            "source_unchanged": not changed,
            "changed_source_files": changed,
            "jump_phases_observed": sorted(jump_phases),
            "note": "course controller demonstration; reset segments are discontinuous; no PPO or obstacle-traversal success claim",
        }
        _json(output / "summary.json", summary)
        _json(
            output / "manifest.json",
            {path.name: _sha(path) for path in sorted(output.iterdir()) if path.is_file()},
        )
    return summary


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seconds", type=float, default=600.0)
    parser.add_argument("--zone", choices=tuple(D1_COURSE_SPAWNS), default="start")
    parser.add_argument("--baseline", choices=("lqr", "mpc"), default="lqr")
    parser.add_argument(
        "--headless", action="store_true", help="zero-command recording without GUI"
    )
    args = parser.parse_args(argv)
    if args.output.exists():
        parser.error("output directory already exists")
    if not math.isfinite(args.seconds) or args.seconds <= 0:
        parser.error("seconds must be finite and positive")
    simulation = D1InteractiveSimulation(
        baseline=args.baseline, arena="course", state_mode="oracle"
    )
    print(
        "Course LQR/MPC with oracle state, no PPO. W/S drive; Q/E set heading; Space jump; "
        "R resets upright at current zone; X cancels; T/G height; A/D side stepping unavailable; "
        "1..6 zones; Esc exits.",
        flush=True,
    )
    summary = run(
        simulation,
        args.output,
        seconds=args.seconds,
        zone=args.zone,
        viewer_factory=None if args.headless else KeyboardViewer,
        realtime=not args.headless,
    )
    print(json.dumps(summary, indent=2, allow_nan=False))
    return 0 if summary["source_unchanged"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
