"""Run the common D1 Gym loop; open a viewer only with --keyboard.

Hold W/S: forward/reverse, A/D: left/right yaw, R/F: body clearance.
Release motion keys or leave window focus to clear requested motion. Space
requests zero speed; Escape ends the rollout. Jumping is not implemented.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import sys
import tarfile
import threading
import time
from collections.abc import Callable
from contextlib import nullcontext
from copy import copy
from pathlib import Path

import numpy as np

from wheel_legged_control.d1.control_loop import D1MotionCommand
from wheel_legged_control.d1.locomotion_checkpoint import load_locomotion_policy

ROOT = Path(__file__).resolve().parents[1]


class KeyboardCommands:
    """Thread-safe bounded targets; no integration or simulator access.

    Core pulse/timeout logic was generated by Claude Opus and locally adapted.
    A timeout only clears requested motion; braking still belongs to the plant
    and controller. Height keys neither refresh nor revive expired motion.
    """

    VX_STEP, VX_MIN, VX_MAX = 0.05, -0.20, 0.30
    YAW_STEP, YAW_LIMIT = 0.05, 0.25
    CLR_STEP, CLR_MIN, CLR_MAX = 0.005, 0.43, 0.48
    KEY_ESCAPE, KEY_SPACE = 256, 32

    def __init__(self, clock: Callable[[], float] = time.monotonic, timeout_s: float = 0.8):
        if not callable(clock):
            raise TypeError("clock must be callable")
        if isinstance(timeout_s, bool) or not math.isfinite(timeout_s) or timeout_s <= 0:
            raise ValueError("timeout_s must be finite and positive")
        self._clock, self._timeout_s = clock, float(timeout_s)
        self._lock = threading.Lock()
        self._vx = self._yaw = 0.0
        self._clearance = 0.455
        self._deadline: float | None = None
        self._stopped = False

    @staticmethod
    def _clamp(value, low, high):
        return round(min(high, max(low, value)), 6)

    def _expire(self):
        if self._deadline is not None and self._clock() >= self._deadline:
            self._deadline = None
            self._vx = self._yaw = 0.0

    def key_callback(self, keycode: int):
        with self._lock:
            self._expire()
            if keycode == self.KEY_ESCAPE:
                self._stopped = True
                self._vx = self._yaw = 0.0
                self._deadline = None
                return
            if self._stopped:
                return
            if keycode == self.KEY_SPACE:
                self._vx = self._yaw = 0.0
                self._deadline = None
                return
            if keycode == ord("W"):
                self._vx = self._clamp(self._vx + self.VX_STEP, self.VX_MIN, self.VX_MAX)
            elif keycode == ord("S"):
                self._vx = self._clamp(self._vx - self.VX_STEP, self.VX_MIN, self.VX_MAX)
            elif keycode == ord("A"):
                self._yaw = self._clamp(self._yaw + self.YAW_STEP, -self.YAW_LIMIT, self.YAW_LIMIT)
            elif keycode == ord("D"):
                self._yaw = self._clamp(self._yaw - self.YAW_STEP, -self.YAW_LIMIT, self.YAW_LIMIT)
            elif keycode in (ord("R"), ord("F")):
                delta = self.CLR_STEP if keycode == ord("R") else -self.CLR_STEP
                self._clearance = self._clamp(self._clearance + delta, self.CLR_MIN, self.CLR_MAX)
                return
            else:
                return
            self._deadline = self._clock() + self._timeout_s

    def __call__(self, simulation_time_s: float) -> D1MotionCommand:
        if not math.isfinite(simulation_time_s) or simulation_time_s < 0:
            raise ValueError("simulation_time_s must be finite and non-negative")
        with self._lock:
            self._expire()
            return D1MotionCommand(self._vx, self._yaw, self._clearance)

    @property
    def stopped(self) -> bool:
        with self._lock:
            return self._stopped


class RecordedCommands:
    """Replay actual per-tick CSV commands; never rescale or interpolate them.

    The final target is held for the terminal observation, which was not an
    executed command in the recording. Reproduction also needs the same seed,
    source, terrain, dynamics, policy and history settings from protocol.json.
    """

    def __init__(self, path: Path):
        self.path = Path(path)
        with self.path.open(newline="") as stream:
            rows = list(csv.DictReader(stream))
        if not rows:
            raise ValueError("command CSV must contain executed control ticks")
        self._commands = []
        for tick, row in enumerate(rows):
            try:
                recorded_time = float(row["decision_time_s"])
                command = D1MotionCommand(
                    float(row["command_vx_mps"]),
                    float(row["command_yaw_rps"]),
                    float(row["command_clearance_m"]),
                )
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"invalid command CSV row {tick + 2}") from exc
            if not math.isfinite(recorded_time) or abs(recorded_time - tick * 0.01) > 1e-9:
                raise ValueError("command CSV must start at zero with consecutive 10 ms ticks")
            self._commands.append(command)
        self.duration_s = len(self._commands) * 0.01

    def __call__(self, simulation_time_s):
        if (
            not math.isfinite(simulation_time_s)
            or not 0 <= simulation_time_s <= self.duration_s + 1e-9
        ):
            raise ValueError("command replay time is outside the recorded episode")
        tick = round(simulation_time_s / 0.01)
        if abs(tick * 0.01 - simulation_time_s) > 1e-9:
            raise ValueError("command replay requires a 10 ms decision time")
        return self._commands[min(tick, len(self._commands) - 1)]


def _sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _write_json(path, value):
    with path.open("x") as stream:
        stream.write(json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n")


def _snapshot(output):
    paths = {Path(__file__).resolve()}
    for module in tuple(sys.modules.values()):
        file = getattr(module, "__file__", None)
        if file and str(ROOT / "src/wheel_legged_control") in file and file.endswith(".py"):
            paths.add(Path(file).resolve())
        if (
            file
            and Path(file).name in ("d1_keyboard_commands.py", "d1_keyboard_viewer.py", "d1_terrain_display.py")
            and Path(file).resolve().parent == ROOT / "scripts"
        ):
            paths.add(Path(file).resolve())
    hashes = {str(path.relative_to(ROOT)): _sha256(path) for path in sorted(paths)}
    with tarfile.open(output / "source.tar.gz", "w:gz") as archive:
        for path in sorted(paths):
            archive.add(path, arcname=str(path.relative_to(ROOT)), recursive=False)
    assets = {
        str(path.relative_to(ROOT)): _sha256(path)
        for path in sorted((ROOT / "src/wheel_legged_control/d1/assets").rglob("*"))
        if path.is_file() and path.suffix.lower() in {".xml", ".urdf", ".stl"}
    }
    return hashes, assets


def run(env, output: Path, *, seed=17, policy_path=None, metadata_path=None, keyboard=None):
    """Execute one already-constructed Gym task; return a measured summary.

    Policy inference receives only env-emitted observations (including the same
    history wrapper as training). All truth below is logging, never policy input.
    The caller transfers ownership of env; this function closes it on every exit.
    """
    import mujoco

    output = Path(output)
    if output.exists():
        env.close()
        raise FileExistsError(output)
    if (policy_path is None) != (metadata_path is None):
        env.close()
        raise ValueError("policy_path and metadata_path must be supplied together")
    try:
        held_keyboard = keyboard is not None and hasattr(keyboard, "update_pressed")
        if held_keyboard:
            if __package__:
                from .d1_keyboard_viewer import KeyboardViewer
            else:
                from d1_keyboard_viewer import KeyboardViewer
        observation, _ = env.reset(seed=seed)
        policy = (
            None if policy_path is None else load_locomotion_policy(policy_path, metadata_path, env)
        )
        output.mkdir(parents=True)
        base = env.unwrapped
        source_hashes, asset_hashes = _snapshot(output)
        # Keep the exact compiled collision model for rendering. Rebuilding
        # from later Python/URDF versions is not an honest recorded replay.
        mujoco.mj_saveModel(base.plant.model, str(output / "model.mjb"), None)
        protocol = {
            "schema": "d1-locomotion-rollout-v1",
            "seed": seed,
            "episode": base.episode_metadata,
            "observation_schema": env.get_wrapper_attr("observation_schema"),
            "history": getattr(
                env,
                "history_metadata",
                {"history_length": 1, "observation_dim": env.observation_space.shape[0]},
            ),
            "policy": "zero_residual" if policy is None else "trusted_local_ppo",
            "model_sha256": None if policy is None else _sha256(policy_path),
            "compiled_model_sha256": _sha256(output / "model.mjb"),
            "checkpoint_metadata": None
            if policy is None
            else json.loads(Path(metadata_path).read_text()),
            "keyboard": keyboard is not None,
            "keyboard_input": "held_keys_glfw_v1"
            if held_keyboard
            else "legacy_pulses"
            if keyboard is not None
            else None,
            "command_csv_sha256": _sha256(base.command_source.path)
            if isinstance(base.command_source, RecordedCommands)
            else None,
            "action_record": "policy_action is policy-returned, not latent Gaussian; raw_action/applied_action are physical residual channels before/after clipping",
            "state_record": "qpos/qvel and time include reset, then each completed control interval",
            "source_sha256": source_hashes,
            "asset_sha256": asset_hashes,
        }
        _write_json(output / "protocol.json", protocol)
        if keyboard is None:
            viewer_context = nullcontext(None)
        else:
            # Viewer synchronization/UI must not alter the control plant's
            # integrator history or physics parameters.
            viewer_model = copy(base.plant.model)
            viewer_data = mujoco.MjData(viewer_model)
            mujoco.mj_copyData(viewer_data, viewer_model, base.plant.measurement_data)
            if held_keyboard:
                terrain = base.episode_metadata.get("terrain", {})
                label = (
                    f"{terrain.get('layout', 'road')} | slope {terrain.get('slope_deg', 0):g} deg | "
                    f"ripples {1000 * terrain.get('ripple_amplitude_m', 0):g} mm | "
                    f"step {1000 * terrain.get('step_height_m', 0):g} mm"
                    if isinstance(terrain, dict)
                    else "recorded terrain"
                )
                viewer_context = KeyboardViewer(
                    viewer_model, viewer_data, keyboard, terrain_label=label
                )
            else:
                # Keep the old callback interface usable for recorded pulse tests.
                import mujoco.viewer

                viewer_context = mujoco.viewer.launch_passive(
                    viewer_model, viewer_data, key_callback=keyboard.key_callback
                )
        rows, rewards, actions, applied, motor_torques, policy_actions = [], [], [], [], [], []
        states = [base.plant.measurement_data.qpos.copy()]
        velocities = [base.plant.measurement_data.qvel.copy()]
        times, observations = [0.0], [observation.copy()]
        reason, terminated, truncated = "not_started", False, False
        last_info = {}
        wall_start = time.monotonic()
        try:
            with viewer_context as viewer:
                if viewer is not None:
                    if not held_keyboard:
                        viewer.cam.distance = 2.5
                    viewer.cam.lookat[:] = base.plant.base_position
                while True:
                    if held_keyboard:
                        viewer.poll(times[-1])
                    if keyboard is not None and keyboard.stopped:
                        reason = "keyboard_escape"
                        break
                    if viewer is not None and not viewer.is_running():
                        reason = "viewer_closed"
                        break
                    started = time.monotonic()
                    action = (
                        np.zeros(env.action_space.shape, dtype=np.float32)
                        if policy is None
                        else policy.predict(observation, deterministic=True)[0]
                    )
                    observation, reward, terminated, truncated, info = env.step(action)
                    transition = base.last_transition
                    command = transition.decision.motion_command
                    row = {
                        "tick": transition.receipt.tick,
                        "decision_time_s": transition.decision.context.proposal.control_time_s,
                        "measurement_time_s": transition.decision.context.state.measurement_time_s,
                        "command_vx_mps": command.forward_velocity_mps,
                        "command_yaw_rps": command.yaw_rate_rps,
                        "command_clearance_m": command.clearance_m,
                        **info["metrics"],
                        "reward": reward,
                        "terminated": terminated,
                        "truncated": truncated,
                        **{f"reward_{name}": value for name, value in info["reward_terms"].items()},
                    }
                    for index, (raw, sent) in enumerate(
                        zip(
                            transition.raw_action, transition.receipt.normalized_action, strict=True
                        )
                    ):
                        row[f"action_returned_{index}"] = float(raw)
                        row[f"action_applied_{index}"] = float(sent)
                    for index, value in enumerate(action):
                        row[f"policy_action_{index}"] = float(value)
                    rows.append(row)
                    rewards.append(reward)
                    actions.append(transition.raw_action)
                    applied.append(transition.receipt.normalized_action)
                    policy_actions.append(np.asarray(action).copy())
                    motor_torques.append(
                        np.asarray(
                            [
                                trace.applied_nm
                                for trace in base.plant.last_control_interval_actuator_traces
                            ]
                        )
                    )
                    states.append(base.plant.measurement_data.qpos.copy())
                    velocities.append(base.plant.measurement_data.qvel.copy())
                    times.append(transition.truth.control_time_s)
                    observations.append(observation.copy())
                    last_info = info
                    if viewer is not None:
                        with viewer.lock():
                            mujoco.mj_copyData(
                                viewer_data, viewer_model, base.plant.measurement_data
                            )
                            viewer.cam.lookat[:] = transition.truth.base_position
                        if held_keyboard:
                            viewer.set_status(command, transition.truth.control_time_s)
                        viewer.sync()
                    if terminated or truncated:
                        reason = info["terminal_reason"]
                        break
                    if viewer is not None:
                        time.sleep(max(0, base.plant.control_dt - (time.monotonic() - started)))
        except KeyboardInterrupt:
            reason = "keyboard_interrupt"
        finally:
            # Preserve partial completed intervals even if a later step fails.
            if held_keyboard:
                with (output / "keyboard_events.jsonl").open("x") as stream:
                    for event in viewer_context.events:
                        stream.write(json.dumps(event, sort_keys=True, allow_nan=False) + "\n")
            with (output / "telemetry.csv").open("x", newline="") as stream:
                if rows:
                    writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
                    writer.writeheader()
                    writer.writerows(rows)
            np.savez_compressed(
                output / "states.npz",
                qpos=np.asarray(states),
                qvel=np.asarray(velocities),
                time_s=np.asarray(times),
                observation=np.asarray(observations),
                policy_action=np.asarray(policy_actions).reshape(-1, env.action_space.shape[0]),
                raw_action=np.asarray(actions).reshape(-1, base.physical_action_size),
                applied_action=np.asarray(applied).reshape(-1, base.physical_action_size),
                actuator_applied_nm=np.asarray(motor_torques).reshape(
                    -1, base.plant.physics_steps, 16
                ),
            )

        def rmse(name):
            return None if not rows else float(np.sqrt(np.mean([row[name] ** 2 for row in rows])))

        changed = [name for name, digest in source_hashes.items() if _sha256(ROOT / name) != digest]
        summary = {
            "steps": len(rows),
            "duration_s": times[-1],
            "requested_duration_s": base.episode_seconds,
            "completed": bool(truncated and not terminated),
            "stop_reason": reason,
            "return": float(sum(rewards)),
            "wall_seconds": time.monotonic() - wall_start,
            "velocity_rmse_mps": rmse("velocity_error_mps"),
            "yaw_rate_rmse_rps": rmse("yaw_rate_error_rps"),
            "height_rmse_m": rmse("height_error_m"),
            "terrain_exposure": last_info.get("terrain_exposure"),
            "source_unchanged": not changed,
            "changed_source_files": changed,
            "status_note": "development rollout; completion is not a tracking-quality or sim2real claim",
        }
        _write_json(output / "summary.json", summary)
        _write_json(
            output / "manifest.json",
            {path.name: _sha256(path) for path in sorted(output.iterdir()) if path.is_file()},
        )
        return summary
    finally:
        env.close()


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, required=True, help="new directory; never overwritten"
    )
    parser.add_argument("--baseline", choices=("wheel_leg", "lqr", "mpc"), default="wheel_leg")
    parser.add_argument("--action-mode", choices=("shared2", "independent8"))
    parser.add_argument("--wheel-kp", type=float)
    parser.add_argument("--wheel-ki", type=float)
    parser.add_argument("--yaw-feedback-gain", type=float)
    parser.add_argument(
        "--leg-feedback-scale", type=float, help="multiplies the nominal leg PD pair (80/3)"
    )
    parser.add_argument(
        "--attitude-feedback-scale",
        type=float,
        help="multiplies the nominal body attitude pair (180/24)",
    )
    parser.add_argument(
        "--seconds", type=float, help="default 60; command replay defaults to CSV duration"
    )
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--history-length", type=int, default=1)
    parser.add_argument(
        "--command-mode", choices=("random", "development", "holdout"), default="development"
    )
    inputs = parser.add_mutually_exclusive_group()
    inputs.add_argument(
        "--keyboard", action="store_true", help="explicitly open a local interactive viewer"
    )
    inputs.add_argument(
        "--command-csv", type=Path, help="replay decision-time commands from telemetry.csv"
    )
    parser.add_argument(
        "--policy",
        type=Path,
        help="trusted local SB3 PPO zip; never download/load untrusted pickles",
    )
    parser.add_argument("--metadata", type=Path, help="required validated v3 checkpoint sidecar")
    terrain = parser.add_mutually_exclusive_group()
    terrain.add_argument(
        "--terrain",
        choices=("flat", "train", "development", "holdout"),
        help="default development for keyboard driving, flat for headless runs",
    )
    terrain.add_argument(
        "--terrain-json", type=Path, help="explicit D1LocomotionTerrainConfig JSON"
    )
    parser.add_argument("--terrain-index", type=int, default=0)
    parser.add_argument("--terrain-suite", choices=("v1", "action_compare_v1"), default="v1")
    parser.add_argument("--source", choices=("oracle", "sensor"), default="sensor")
    parser.add_argument("--sensor-delay-steps", type=int, default=0, help="10 ms measurement steps")
    parser.add_argument("--actuator-delay-steps", type=int, default=0, help="2 ms physics steps")
    parser.add_argument("--actuator-time-constant", type=float, default=0, help="synthetic seconds")
    parser.add_argument(
        "--actuator-gain", type=float, default=1, help="synthetic dimensionless gain"
    )
    return parser


def main(argv=None):
    from wheel_legged_control.d1.actuator_channel import ActuatorChannelConfig
    from wheel_legged_control.d1.locomotion_env import LOCOMOTION_SPAWN_POSITION_M, D1LocomotionEnv
    from wheel_legged_control.d1.locomotion_terrain import (
        D1LocomotionTerrainConfig,
        locomotion_terrain_configs,
    )
    from wheel_legged_control.d1.model import JOINT_TORQUE_LIMIT
    from wheel_legged_control.d1.observation_history import D1ObservationHistory
    from wheel_legged_control.d1.sensor_estimation import D1SensorNoise
    from wheel_legged_control.d1.state_provider import D1StateProviderConfig
    from wheel_legged_control.d1.wheel_leg_controller import D1WheelLegControlConfig

    parser = build_parser()
    args = parser.parse_args(argv)
    if args.action_mode is not None and args.baseline != "wheel_leg":
        parser.error("explicit action mode requires --baseline wheel_leg")
    overrides = {
        name: getattr(args, name)
        for name in (
            "wheel_kp",
            "wheel_ki",
            "yaw_feedback_gain",
            "leg_feedback_scale",
            "attitude_feedback_scale",
        )
        if getattr(args, name) is not None
    }
    if overrides and args.baseline != "wheel_leg":
        parser.error("wheel gains and feedback scales require --baseline wheel_leg")
    try:
        wheel_control = D1WheelLegControlConfig(**overrides) if overrides else None
    except (TypeError, ValueError) as exc:
        parser.error(str(exc))
    if args.output.exists():
        parser.error("output directory already exists")
    if (args.policy is None) != (args.metadata is None):
        parser.error("--policy and --metadata must be supplied together")
    if args.seed < 0 or args.history_length < 1 or args.sensor_delay_steps < 0:
        parser.error("seed/delay must be non-negative; history must be positive")
    if args.source == "oracle" and args.sensor_delay_steps:
        parser.error("oracle does not accept sensor delay")
    if args.terrain is None:
        args.terrain = "development" if args.keyboard else "flat"
    if args.terrain_json is not None:
        terrain = D1LocomotionTerrainConfig.from_json(args.terrain_json.read_text())
    elif args.terrain == "flat":
        if args.terrain_index:
            parser.error("flat terrain has only index 0")
        terrain = D1LocomotionTerrainConfig()
    else:
        configs = locomotion_terrain_configs(args.terrain, suite=args.terrain_suite)
        if not 0 <= args.terrain_index < len(configs):
            parser.error("terrain index is out of range for the chosen split")
        terrain = configs[args.terrain_index]
    commands = RecordedCommands(args.command_csv) if args.command_csv else None
    keyboard = None
    if args.keyboard:
        if __package__:
            from .d1_keyboard_commands import HeldKeyboardCommands
        else:
            from d1_keyboard_commands import HeldKeyboardCommands
        keyboard = HeldKeyboardCommands()
    seconds = (
        args.seconds if args.seconds is not None else commands.duration_s if commands else 60.0
    )
    if commands is not None and not math.isclose(
        seconds, commands.duration_s, abs_tol=1e-9, rel_tol=0
    ):
        parser.error("--seconds must match recorded command duration")
    provider = (
        D1StateProviderConfig("oracle")
        if args.source == "oracle"
        else D1StateProviderConfig(
            "imu_encoder_fusion",
            sensor_delay_steps=args.sensor_delay_steps,
            initial_position_m=LOCOMOTION_SPAWN_POSITION_M,
            initial_rpy_rad=(0, 0, 0),
            sensor_noise=D1SensorNoise(
                gyro_std_rad_s=0.002,
                accelerometer_std_m_s2=0.03,
                encoder_position_std_rad=0.0005,
                encoder_velocity_std_rad_s=0.005,
            ),
        )
    )
    if args.policy is not None:
        import torch

        torch.set_num_threads(1)
    env = D1ObservationHistory(
        D1LocomotionEnv(
            baseline=args.baseline,
            action_mode=args.action_mode,
            episode_seconds=seconds,
            terrain=terrain,
            command_mode=args.command_mode,
            command_source=keyboard or commands,
            provider_config=provider,
            wheel_leg_control=wheel_control,
            actuator_config=ActuatorChannelConfig(
                torque_limit_nm=tuple(JOINT_TORQUE_LIMIT),
                delay_steps=args.actuator_delay_steps,
                time_constant_s=args.actuator_time_constant,
                gain=args.actuator_gain,
            ),
        ),
        args.history_length,
    )
    if keyboard is not None:
        print(
            "Hold W/S to drive, A/D to turn, R/F for height; release to stop request. "
            "Space stops, C resets camera, Esc exits. Mouse drag or wheel changes view. No jump.",
            flush=True,
        )
    summary = run(
        env,
        args.output,
        seed=args.seed,
        policy_path=args.policy,
        metadata_path=args.metadata,
        keyboard=keyboard,
    )
    print(json.dumps(summary, indent=2, allow_nan=False))
    return 0 if summary["completed"] and summary["source_unchanged"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
